package com.cuize.commons.dao.product.domain;

import java.util.Date;

public class ShopProductPackdtl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_product_packdtl.id
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_product_packdtl.product_id
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_product_packdtl.pack_product_id
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    private Integer packProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_product_packdtl.pack_price
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    private Double packPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_product_packdtl.is_main
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    private Integer isMain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_product_packdtl.create_time
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_product_packdtl.update_time
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_product_packdtl.version
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_product_packdtl.separate_refund
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    private Integer separateRefund;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_product_packdtl.id
     *
     * @return the value of shop_product_packdtl.id
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_product_packdtl.id
     *
     * @param id the value for shop_product_packdtl.id
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_product_packdtl.product_id
     *
     * @return the value of shop_product_packdtl.product_id
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_product_packdtl.product_id
     *
     * @param productId the value for shop_product_packdtl.product_id
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_product_packdtl.pack_product_id
     *
     * @return the value of shop_product_packdtl.pack_product_id
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    public Integer getPackProductId() {
        return packProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_product_packdtl.pack_product_id
     *
     * @param packProductId the value for shop_product_packdtl.pack_product_id
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    public void setPackProductId(Integer packProductId) {
        this.packProductId = packProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_product_packdtl.pack_price
     *
     * @return the value of shop_product_packdtl.pack_price
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    public Double getPackPrice() {
        return packPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_product_packdtl.pack_price
     *
     * @param packPrice the value for shop_product_packdtl.pack_price
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    public void setPackPrice(Double packPrice) {
        this.packPrice = packPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_product_packdtl.is_main
     *
     * @return the value of shop_product_packdtl.is_main
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    public Integer getIsMain() {
        return isMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_product_packdtl.is_main
     *
     * @param isMain the value for shop_product_packdtl.is_main
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    public void setIsMain(Integer isMain) {
        this.isMain = isMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_product_packdtl.create_time
     *
     * @return the value of shop_product_packdtl.create_time
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_product_packdtl.create_time
     *
     * @param createTime the value for shop_product_packdtl.create_time
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_product_packdtl.update_time
     *
     * @return the value of shop_product_packdtl.update_time
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_product_packdtl.update_time
     *
     * @param updateTime the value for shop_product_packdtl.update_time
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_product_packdtl.version
     *
     * @return the value of shop_product_packdtl.version
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_product_packdtl.version
     *
     * @param version the value for shop_product_packdtl.version
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_product_packdtl.separate_refund
     *
     * @return the value of shop_product_packdtl.separate_refund
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    public Integer getSeparateRefund() {
        return separateRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_product_packdtl.separate_refund
     *
     * @param separateRefund the value for shop_product_packdtl.separate_refund
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    public void setSeparateRefund(Integer separateRefund) {
        this.separateRefund = separateRefund;
    }
}