package com.cuize.commons.dao.activity.mapper;

import com.cuize.commons.dao.activity.domain.ScheduleSetPrice;
import com.cuize.commons.dao.activity.domain.ScheduleSetPriceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScheduleSetPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_set_price
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    int countByExample(ScheduleSetPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_set_price
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    int deleteByExample(ScheduleSetPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_set_price
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_set_price
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    int insert(ScheduleSetPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_set_price
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    int insertSelective(ScheduleSetPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_set_price
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    List<ScheduleSetPrice> selectByExample(ScheduleSetPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_set_price
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    ScheduleSetPrice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_set_price
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    int updateByExampleSelective(@Param("record") ScheduleSetPrice record, @Param("example") ScheduleSetPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_set_price
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    int updateByExample(@Param("record") ScheduleSetPrice record, @Param("example") ScheduleSetPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_set_price
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    int updateByPrimaryKeySelective(ScheduleSetPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_set_price
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    int updateByPrimaryKey(ScheduleSetPrice record);
}