package com.cuize.commons.dao.order.mapper;

import com.cuize.commons.dao.order.domain.OrderRefund;
import com.cuize.commons.dao.order.domain.OrderRefundExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderRefundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    int countByExample(OrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    int deleteByExample(OrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    int insert(OrderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    int insertSelective(OrderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    List<OrderRefund> selectByExample(OrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    OrderRefund selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    int updateByExampleSelective(@Param("record") OrderRefund record, @Param("example") OrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    int updateByExample(@Param("record") OrderRefund record, @Param("example") OrderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    int updateByPrimaryKeySelective(OrderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_refund
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    int updateByPrimaryKey(OrderRefund record);
}