package com.cuize.commons.dao.product.mapper;

import com.cuize.commons.dao.product.domain.ShopProduct;
import com.cuize.commons.dao.product.domain.ShopProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @mbggenerated Wed Apr 27 17:41:04 CST 2016
     */
    int countByExample(ShopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @mbggenerated Wed Apr 27 17:41:04 CST 2016
     */
    int deleteByExample(ShopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @mbggenerated Wed Apr 27 17:41:04 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @mbggenerated Wed Apr 27 17:41:04 CST 2016
     */
    int insert(ShopProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @mbggenerated Wed Apr 27 17:41:04 CST 2016
     */
    int insertSelective(ShopProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @mbggenerated Wed Apr 27 17:41:04 CST 2016
     */
    List<ShopProduct> selectByExample(ShopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @mbggenerated Wed Apr 27 17:41:04 CST 2016
     */
    ShopProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @mbggenerated Wed Apr 27 17:41:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") ShopProduct record, @Param("example") ShopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @mbggenerated Wed Apr 27 17:41:04 CST 2016
     */
    int updateByExample(@Param("record") ShopProduct record, @Param("example") ShopProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @mbggenerated Wed Apr 27 17:41:04 CST 2016
     */
    int updateByPrimaryKeySelective(ShopProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product
     *
     * @mbggenerated Wed Apr 27 17:41:04 CST 2016
     */
    int updateByPrimaryKey(ShopProduct record);
}