package com.cuize.commons.dao.product.mapper;

import com.cuize.commons.dao.product.domain.ShopProductPackdtl;
import com.cuize.commons.dao.product.domain.ShopProductPackdtlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShopProductPackdtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_packdtl
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    int countByExample(ShopProductPackdtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_packdtl
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    int deleteByExample(ShopProductPackdtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_packdtl
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_packdtl
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    int insert(ShopProductPackdtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_packdtl
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    int insertSelective(ShopProductPackdtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_packdtl
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    List<ShopProductPackdtl> selectByExample(ShopProductPackdtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_packdtl
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    ShopProductPackdtl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_packdtl
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    int updateByExampleSelective(@Param("record") ShopProductPackdtl record, @Param("example") ShopProductPackdtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_packdtl
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    int updateByExample(@Param("record") ShopProductPackdtl record, @Param("example") ShopProductPackdtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_packdtl
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    int updateByPrimaryKeySelective(ShopProductPackdtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop_product_packdtl
     *
     * @mbggenerated Wed Apr 27 17:42:49 CST 2016
     */
    int updateByPrimaryKey(ShopProductPackdtl record);
}