package com.cuize.commons.dao.activity.domain;

import java.util.Date;

public class ActivityAward {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_award.id
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_award.activity_code
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	private String activityCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_award.award_code
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	private String awardCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_award.total_count
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	private Integer totalCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_award.remain_count
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	private Integer remainCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_award.create_time
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_award.probability
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	private Integer probability;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_award.activity_date
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	private String activityDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_award.version
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	private Integer version;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_award.id
	 * @return  the value of activity_award.id
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_award.id
	 * @param id  the value for activity_award.id
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_award.activity_code
	 * @return  the value of activity_award.activity_code
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public String getActivityCode() {
		return activityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_award.activity_code
	 * @param activityCode  the value for activity_award.activity_code
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public void setActivityCode(String activityCode) {
		this.activityCode = activityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_award.award_code
	 * @return  the value of activity_award.award_code
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public String getAwardCode() {
		return awardCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_award.award_code
	 * @param awardCode  the value for activity_award.award_code
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public void setAwardCode(String awardCode) {
		this.awardCode = awardCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_award.total_count
	 * @return  the value of activity_award.total_count
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public Integer getTotalCount() {
		return totalCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_award.total_count
	 * @param totalCount  the value for activity_award.total_count
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public void setTotalCount(Integer totalCount) {
		this.totalCount = totalCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_award.remain_count
	 * @return  the value of activity_award.remain_count
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public Integer getRemainCount() {
		return remainCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_award.remain_count
	 * @param remainCount  the value for activity_award.remain_count
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public void setRemainCount(Integer remainCount) {
		this.remainCount = remainCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_award.create_time
	 * @return  the value of activity_award.create_time
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_award.create_time
	 * @param createTime  the value for activity_award.create_time
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_award.probability
	 * @return  the value of activity_award.probability
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public Integer getProbability() {
		return probability;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_award.probability
	 * @param probability  the value for activity_award.probability
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public void setProbability(Integer probability) {
		this.probability = probability;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_award.activity_date
	 * @return  the value of activity_award.activity_date
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public String getActivityDate() {
		return activityDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_award.activity_date
	 * @param activityDate  the value for activity_award.activity_date
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public void setActivityDate(String activityDate) {
		this.activityDate = activityDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_award.version
	 * @return  the value of activity_award.version
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_award.version
	 * @param version  the value for activity_award.version
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}
}