package com.cuize.commons.dao.activity.domain;

import java.util.Date;

public class ActivityUserctl {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_userctl.id
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_userctl.openid
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	private String openid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_userctl.activity_code
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	private String activityCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_userctl.award_code
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	private String awardCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_userctl.create_time
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_userctl.id
	 * @return  the value of activity_userctl.id
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_userctl.id
	 * @param id  the value for activity_userctl.id
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_userctl.openid
	 * @return  the value of activity_userctl.openid
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public String getOpenid() {
		return openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_userctl.openid
	 * @param openid  the value for activity_userctl.openid
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_userctl.activity_code
	 * @return  the value of activity_userctl.activity_code
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public String getActivityCode() {
		return activityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_userctl.activity_code
	 * @param activityCode  the value for activity_userctl.activity_code
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public void setActivityCode(String activityCode) {
		this.activityCode = activityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_userctl.award_code
	 * @return  the value of activity_userctl.award_code
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public String getAwardCode() {
		return awardCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_userctl.award_code
	 * @param awardCode  the value for activity_userctl.award_code
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public void setAwardCode(String awardCode) {
		this.awardCode = awardCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_userctl.create_time
	 * @return  the value of activity_userctl.create_time
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_userctl.create_time
	 * @param createTime  the value for activity_userctl.create_time
	 * @mbggenerated  Wed Apr 27 16:46:59 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}