package com.cuize.commons.dao.activity.domain;

import java.util.Date;

public class ScheduleSetPrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_set_price.id
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_set_price.product_id
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_set_price.product_code
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    private String productCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_set_price.product_name
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_set_price.update_time
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_set_price.set_price
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    private Double setPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_set_price.create_time
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_set_price.id
     *
     * @return the value of schedule_set_price.id
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_set_price.id
     *
     * @param id the value for schedule_set_price.id
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_set_price.product_id
     *
     * @return the value of schedule_set_price.product_id
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_set_price.product_id
     *
     * @param productId the value for schedule_set_price.product_id
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_set_price.product_code
     *
     * @return the value of schedule_set_price.product_code
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_set_price.product_code
     *
     * @param productCode the value for schedule_set_price.product_code
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_set_price.product_name
     *
     * @return the value of schedule_set_price.product_name
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_set_price.product_name
     *
     * @param productName the value for schedule_set_price.product_name
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_set_price.update_time
     *
     * @return the value of schedule_set_price.update_time
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_set_price.update_time
     *
     * @param updateTime the value for schedule_set_price.update_time
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_set_price.set_price
     *
     * @return the value of schedule_set_price.set_price
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    public Double getSetPrice() {
        return setPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_set_price.set_price
     *
     * @param setPrice the value for schedule_set_price.set_price
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    public void setSetPrice(Double setPrice) {
        this.setPrice = setPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_set_price.create_time
     *
     * @return the value of schedule_set_price.create_time
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_set_price.create_time
     *
     * @param createTime the value for schedule_set_price.create_time
     *
     * @mbggenerated Tue May 17 15:25:39 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}