package com.cuize.commons.dao.order.domain;

import java.util.Date;

public class OrderRefund {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund.id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund.user_name
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund.mobile_phone
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    private String mobilePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund.open_id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund.shop_id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund.shop_product_id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    private Integer shopProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund.third_product_id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    private String thirdProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund.order_id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund.order_detail_id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    private Integer orderDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund.order_no
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund.sub_order_no
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    private String subOrderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund.refund_time
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    private Date refundTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund.refund_price
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    private Double refundPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund.supplier
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    private String supplier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund.third_refund_no
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    private String thirdRefundNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund.third_refund_desc
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    private String thirdRefundDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund.remark
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund.create_time
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund.version
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_refund.status
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund.id
     *
     * @return the value of order_refund.id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund.id
     *
     * @param id the value for order_refund.id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund.user_name
     *
     * @return the value of order_refund.user_name
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund.user_name
     *
     * @param userName the value for order_refund.user_name
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund.mobile_phone
     *
     * @return the value of order_refund.mobile_phone
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund.mobile_phone
     *
     * @param mobilePhone the value for order_refund.mobile_phone
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund.open_id
     *
     * @return the value of order_refund.open_id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund.open_id
     *
     * @param openId the value for order_refund.open_id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund.shop_id
     *
     * @return the value of order_refund.shop_id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund.shop_id
     *
     * @param shopId the value for order_refund.shop_id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund.shop_product_id
     *
     * @return the value of order_refund.shop_product_id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public Integer getShopProductId() {
        return shopProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund.shop_product_id
     *
     * @param shopProductId the value for order_refund.shop_product_id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public void setShopProductId(Integer shopProductId) {
        this.shopProductId = shopProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund.third_product_id
     *
     * @return the value of order_refund.third_product_id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public String getThirdProductId() {
        return thirdProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund.third_product_id
     *
     * @param thirdProductId the value for order_refund.third_product_id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public void setThirdProductId(String thirdProductId) {
        this.thirdProductId = thirdProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund.order_id
     *
     * @return the value of order_refund.order_id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund.order_id
     *
     * @param orderId the value for order_refund.order_id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund.order_detail_id
     *
     * @return the value of order_refund.order_detail_id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public Integer getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund.order_detail_id
     *
     * @param orderDetailId the value for order_refund.order_detail_id
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public void setOrderDetailId(Integer orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund.order_no
     *
     * @return the value of order_refund.order_no
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund.order_no
     *
     * @param orderNo the value for order_refund.order_no
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund.sub_order_no
     *
     * @return the value of order_refund.sub_order_no
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public String getSubOrderNo() {
        return subOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund.sub_order_no
     *
     * @param subOrderNo the value for order_refund.sub_order_no
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public void setSubOrderNo(String subOrderNo) {
        this.subOrderNo = subOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund.refund_time
     *
     * @return the value of order_refund.refund_time
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public Date getRefundTime() {
        return refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund.refund_time
     *
     * @param refundTime the value for order_refund.refund_time
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public void setRefundTime(Date refundTime) {
        this.refundTime = refundTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund.refund_price
     *
     * @return the value of order_refund.refund_price
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public Double getRefundPrice() {
        return refundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund.refund_price
     *
     * @param refundPrice the value for order_refund.refund_price
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public void setRefundPrice(Double refundPrice) {
        this.refundPrice = refundPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund.supplier
     *
     * @return the value of order_refund.supplier
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund.supplier
     *
     * @param supplier the value for order_refund.supplier
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund.third_refund_no
     *
     * @return the value of order_refund.third_refund_no
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public String getThirdRefundNo() {
        return thirdRefundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund.third_refund_no
     *
     * @param thirdRefundNo the value for order_refund.third_refund_no
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public void setThirdRefundNo(String thirdRefundNo) {
        this.thirdRefundNo = thirdRefundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund.third_refund_desc
     *
     * @return the value of order_refund.third_refund_desc
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public String getThirdRefundDesc() {
        return thirdRefundDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund.third_refund_desc
     *
     * @param thirdRefundDesc the value for order_refund.third_refund_desc
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public void setThirdRefundDesc(String thirdRefundDesc) {
        this.thirdRefundDesc = thirdRefundDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund.remark
     *
     * @return the value of order_refund.remark
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund.remark
     *
     * @param remark the value for order_refund.remark
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund.create_time
     *
     * @return the value of order_refund.create_time
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund.create_time
     *
     * @param createTime the value for order_refund.create_time
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund.version
     *
     * @return the value of order_refund.version
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund.version
     *
     * @param version the value for order_refund.version
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_refund.status
     *
     * @return the value of order_refund.status
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_refund.status
     *
     * @param status the value for order_refund.status
     *
     * @mbggenerated Mon May 23 17:07:05 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}