package com.cuize.commons.dao.order.domain;

import java.util.Date;

public class ProductStock {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_stock.product_id
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_stock.product_code
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	private String productCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_stock.product_name
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	private String productName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_stock.poduct_status
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	private Integer poductStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_stock.stock
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	private Integer stock;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_stock.remain
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	private Integer remain;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_stock.create_time
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_stock.update_time
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_stock.version
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	private Integer version;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_stock.product_id
	 * @return  the value of product_stock.product_id
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_stock.product_id
	 * @param productId  the value for product_stock.product_id
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_stock.product_code
	 * @return  the value of product_stock.product_code
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	public String getProductCode() {
		return productCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_stock.product_code
	 * @param productCode  the value for product_stock.product_code
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_stock.product_name
	 * @return  the value of product_stock.product_name
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_stock.product_name
	 * @param productName  the value for product_stock.product_name
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_stock.poduct_status
	 * @return  the value of product_stock.poduct_status
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	public Integer getPoductStatus() {
		return poductStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_stock.poduct_status
	 * @param poductStatus  the value for product_stock.poduct_status
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	public void setPoductStatus(Integer poductStatus) {
		this.poductStatus = poductStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_stock.stock
	 * @return  the value of product_stock.stock
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	public Integer getStock() {
		return stock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_stock.stock
	 * @param stock  the value for product_stock.stock
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	public void setStock(Integer stock) {
		this.stock = stock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_stock.remain
	 * @return  the value of product_stock.remain
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	public Integer getRemain() {
		return remain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_stock.remain
	 * @param remain  the value for product_stock.remain
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	public void setRemain(Integer remain) {
		this.remain = remain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_stock.create_time
	 * @return  the value of product_stock.create_time
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_stock.create_time
	 * @param createTime  the value for product_stock.create_time
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_stock.update_time
	 * @return  the value of product_stock.update_time
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_stock.update_time
	 * @param updateTime  the value for product_stock.update_time
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_stock.version
	 * @return  the value of product_stock.version
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	public Integer getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_stock.version
	 * @param version  the value for product_stock.version
	 * @mbggenerated  Fri May 20 18:19:39 CST 2016
	 */
	public void setVersion(Integer version) {
		this.version = version;
	}
}